Add gh actions for pr
nitishm/go-rejson pull request #58
Opened 2022-01-13 14:48 UTC by breno12321

2022-01-13 19:20 UTC, Shivam010 approved these changes

2022-01-13 19:20 UTC, Shivam010 commented on .github/workflows/analysis.yml
> +on: [push, pull_request]
Yeah, I forgot we kept it to be run only on push earlier. 

Now, I don't think there's any issue in adding pull requests into the scopes. Thanks

2022-01-13 19:34 UTC, Shivam010 requested changes
@breno12321 
Let's continue the encoding issue in #57 and merge this here with only the workflow yaml changes.

Can you remove your changes from `rjs/helper.go` file, so that we can merge this?

2022-01-14 01:06 UTC, breno12321 commented
Oh sorry I thought I didn't sent them together

2022-01-14 11:37 UTC, Shivam010 approved these changes

2022-01-14 12:04 UTC, breno12321 commented
@Shivam010 Uhm why it still don't pass even though its just github actions change 🤔

2022-01-14 13:37 UTC, Shivam010 commented
It's the version issue, we are using the latest version of `redislabs/rejson` (i.e 2.0.6)

Redislabs have changed some command responses after `1.0.8` which is causing failures in our tests. I have run them locally with 1.0.8, they are working.

For now, limiting the support to 1.0.8 and merging changes

2022-01-14 13:38 UTC, Shivam010 commented
Ignoring the `code-analysis / staticcheck` too.

2022-01-14 13:38 UTC, merged

2022-01-14 13:39 UTC, breno12321 commented
Thanks <3