add support for redis v9
nitishm/go-rejson pull request #72
Opened 2023-03-13 12:23 UTC by YafimK

This updates the support for go-redis libary to latest v9

2023-03-18 20:26 UTC, Shivam010 requested changes
The changes look good to me. Thanks @YafimK for the PR.

Additionally, it seems that with go-redis@v9 we can support Go versions: [ 1.13, 1.14, 1.15 ], which is causing tests to fail. **Can you update the go version in the workflow file to [ 1.20 ] ?**
https://github.com/nitishm/go-rejson/blob/master/.github/workflows/test.yml#L9

Also, the linters in code-analysis.yml are also failing due to some version issues. Are we willing to look into it? We can have a separate PR also for the linters fix.

2023-03-19 12:03 UTC, Shivam010 commented on .github/workflows/test.yml
> +        go_version: [ 1.13, 1.14, 1.15, 1.20 ]
```suggestion
        go_version: [ 1.20 ]
```

2023-03-31 05:09 UTC, d0x7 commented
Seems all requested changes were made to me, right? When is this due to merge? I'd be more than happy to be able to use this.

2023-03-31 06:01 UTC, Shivam010 approved these changes

2023-03-31 06:02 UTC, Shivam010 commented
Sorry for the delay. Looks like we are all set. Thanks for the PR @YafimK

2023-03-31 06:02 UTC, merged